"""Device provider protocols for Commercial V1 (simulation and future real adapters)."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Protocol, runtime_checkable

DeviceConnectionState = Literal["disconnected", "connecting", "connected", "error"]


@dataclass(slots=True)
class DeviceCommandResult:
    """Result of a device operation."""

    success: bool
    message: str
    dry_run: bool = True


@dataclass(slots=True)
class DeviceStateModel:
    """Normalized device state for UI sync."""

    device_id: str
    kind: str
    display_name: str
    connection_state: DeviceConnectionState
    status_label: str
    summary: str
    last_message: str = ""


@runtime_checkable
class MotionDeviceProtocol(Protocol):
    def connect(self) -> DeviceCommandResult: ...
    def disconnect(self) -> DeviceCommandResult: ...
    def refresh(self) -> DeviceCommandResult: ...
    def configure(self, config: dict) -> DeviceCommandResult: ...
    def test_connection(self) -> DeviceCommandResult: ...
    def get_status(self) -> DeviceStateModel: ...
    def get_last_message(self) -> str: ...


@runtime_checkable
class SpectrumDeviceProtocol(Protocol):
    def connect(self) -> DeviceCommandResult: ...
    def disconnect(self) -> DeviceCommandResult: ...
    def refresh(self) -> DeviceCommandResult: ...
    def configure(self, config: dict) -> DeviceCommandResult: ...
    def test_connection(self) -> DeviceCommandResult: ...
    def get_status(self) -> DeviceStateModel: ...
    def get_last_message(self) -> str: ...


@runtime_checkable
class CameraDeviceProtocol(Protocol):
    def connect(self) -> DeviceCommandResult: ...
    def disconnect(self) -> DeviceCommandResult: ...
    def refresh(self) -> DeviceCommandResult: ...
    def configure(self, config: dict) -> DeviceCommandResult: ...
    def test_connection(self) -> DeviceCommandResult: ...
    def get_status(self) -> DeviceStateModel: ...
    def get_last_message(self) -> str: ...


@runtime_checkable
class DeviceProviderProtocol(Protocol):
    """Aggregate provider for all device types."""

    def connect_all(self) -> list[DeviceCommandResult]: ...
    def disconnect_all(self) -> list[DeviceCommandResult]: ...
    def refresh_all(self) -> list[DeviceCommandResult]: ...
    def test_connection(self, device_id: str) -> DeviceCommandResult: ...
    def configure(self, device_id: str, config: dict) -> DeviceCommandResult: ...
    def list_states(self) -> list[DeviceStateModel]: ...
