from __future__ import annotations
from typing import Protocol

class MotionDriver(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def home(self) -> None: ...
    def move_to(self, x: float, y: float, z: float, feed: float) -> None: ...
